React develop
wooz1ewu/ITechArt_Front-End pull request #6
Opened 2021-07-13 14:39 UTC by wooz1ewu

# Overview  
> 1. Create project using create-react-app.  
> 2. Implement Note-info displaying.  
> 3. Implement full info displaying of active(selected) note.  
> 4. Add prop-types checkings.  
> 5. Implement storing of active note via useState hook.  
> 6. Use material-ui.
> 7. Implement project structure.  

# Changes  
> 1. Project structure was created using BEM.
> 2. MyNotes page's side panel and active-note display panel implemented.  
> 3. NoteList, NoteItem, DisplayedNote components were implemented so to display all the necessary info.
> 4. Styles were added and implemented using constant-objects.
> 5. Active note and note list are stored using useState hook.
> 6. Close button implemented with material-ui button.  
> 7. Prop-types checkings implemented using prop-types module.  
> 8. App was deployed on githib pages.

# How to test
> 1. Load [page](https://wooz1ewu.github.io/ITechArt_Front-End/), check if notes are displayed.   
> 1.1. Check if "Choose a note to display" message shown while note is not selected.
> 2. Set active note by clicking on it.  
> 2.1. Check if active note is illuminated.  
> 2.2. Check if active note information is displayed on display-panel.

2021-07-16 11:30 UTC, k-krasilnikova requested changes
Good job, but some changes needed

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/components/DisplayedNote/DisplayedNote.jsx
> +function DisplayedNote({ activeNote }) {
Let's declare all the components using arrow functions:
`const DisplayedNote = ({ activeNote }) => {`

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/components/DisplayedNote/DisplayedNote.jsx
> +  return (
In case there's nothing to get/calculate, there is no reason to write an additional `return` statement. We can write just:
```
const DisplayedNote = ({ activeNote }) => (
  <div style={Styles.wrapper}>
    ...
  </div>
)
```

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/components/DisplayedNote/DisplayedNote.jsx
> +      {activeNote === null ? (
I think we can leave just: 
` {activeNote ? ( ...`

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/components/NoteList/NoteItem/NoteItem.jsx
> +function NoteItem({ note, onSelect }) {
`const NoteItem = ({ note, onSelect }) = {`

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/components/NoteList/NoteItem/NoteItem.jsx
> +import { Button } from '@material-ui/core';
Clear imports please.

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/components/NoteList/NoteItem/NoteItem.jsx
> +  }
I think we can reduce amount of code here:
```suggestion
  const wrapperStyle = { ...Styles.itemWrapper,  ...(!isActive&& {...Styles.itemWrapper_active}) };
```

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/components/NoteList/NoteItem/NoteItem.jsx
> +    <div style={totalWrapperStyle} onClick={onSelect.bind(null, note)}>
Do we really need to use `bind` here?

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/components/NoteList/NoteItem/NoteItem.jsx
> +          {note.description.length < 20
Move all the logic to a separate util function inside the `utils` folder

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/components/NoteList/NoteList.jsx
> +}
1. Arrow function
2. Remove `return` statement
3. Remove inside the `map` unexpected `return`
4. Empty tag usage
```suggestion
const NoteList = ({ style, notes, onSelect }) => (
    <div style={style}>
      {notes.map((note, index) => (
         <NoteItem note={note} key={index} onSelect={onSelect} />
      ))}
    </div>
  );
```

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/pages/myNotes/myNotes.jsx
> +  const notes = [
All the constants with "collection" logic should be named with UPPERCASE

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/pages/myNotes/myNotes.jsx
> +function MyNotes() {
Arrow func

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/pages/myNotes/myNotes.jsx
> +  function onSelectNote(selectedNote) {
Arrow function will be good here

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/pages/myNotes/myNotes.jsx
> +        if (note === selectedNote) {
Are you trying to compare OBJECTS by their links?? What we will do in case data will be from server??? Maybe it will be better to compare their IDS instead????

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/pages/myNotes/myNotes.jsx
> +          note.isActive = true;
Are you trying to change CONSTANT PROPS? Try to find better solution to handle active note.

2021-07-16 11:30 UTC, k-krasilnikova commented on note-app/src/pages/myNotes/myNotes.jsx
> +        ></NoteList>
```suggestion
        <NoteList
          style={Styles.noteList}
          notes={noteList}
          onSelect={onSelectNote}
        />
```

2021-07-16 20:01 UTC, wooz1ewu commented on note-app/src/components/NoteList/NoteItem/NoteItem.jsx
> +    <div style={totalWrapperStyle} onClick={onSelect.bind(null, note)}>
Yep, cause we need to pass note parameter to the function somehow. I couldn't find a better solution

2021-07-22 13:04 UTC, k-krasilnikova approved these changes
Approved, but some changes required, see comments please and after fixing them - merge PR.

2021-07-22 13:04 UTC, k-krasilnikova commented on note-app/src/components/DisplayedNote/DisplayedNote.jsx
> +    )}
Try to avoid using an unnecessary negation, it's can be hard to read the code. No need to make any changes, just note for the future:
```suggestion
    {activeNote ? (
      <div>
        <p style={styles.noteTitle}>{activeNote.title}</p>
        <p style={styles.noteDescription}>{activeNote.description}</p>
        <p style={styles.noteCreation}>{activeNote.creation}</p>
      </div>
    ) : (
      <p style={styles.noNoteMessage}>Select note to display</p>
    )}
```

2021-07-22 13:04 UTC, k-krasilnikova commented on note-app/src/config/constants/maxDescriptionLength.js
> +export default MAX_DESCRIPTION_LENGTH;
You can create only one file `constants/index.js` and declare most of the constants inside:
```
export const MAX_DESCRIPTION_LENGTH = 20;
export const TEST = 'test';
```

2021-07-22 13:04 UTC, k-krasilnikova commented on note-app/src/pages/myNotes/myNotes.jsx
> +  const NOTES = [
Move `NOTES` to constants

2021-07-23 12:15 UTC, merged